In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset= pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep= dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.60152693 0.58533254 0.56889677 0.59887047
        nan        nan 0.61134864 0.58812662 0.55900752 0.57212075
        nan        nan 0.57192183 0.62043984 0.64513497 0.59226264
        nan        nan 0.59901353 0.60359498 0.62254885 0.59736466]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'best'}

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003835,0.001468,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.004283,0.002146,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.011032,0.001962,0.006568,0.001950,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.753494,0.583707,0.687834,0.577228,0.588464,0.638145,0.070593,3
3,0.007712,0.000968,0.005353,0.000442,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.730080,0.533651,0.602061,0.573787,0.618192,0.611554,0.065845,8
4,0.008977,0.001368,0.005517,0.000849,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.749017,0.624747,0.626618,0.590820,0.652580,0.648756,0.053833,2
5,0.009679,0.002530,0.006815,0.002047,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.701588,0.592487,0.706725,0.595991,0.513546,0.622067,0.073242,6
6,0.001887,0.000409,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002506,0.000685,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.009245,0.001069,0.005107,0.000816,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.637867,0.558071,0.561803,0.629233,0.700330,0.617461,0.053004,7
9,0.010210,0.001499,0.006105,0.001576,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.717205,0.475792,0.599209,0.650558,0.557754,0.600104,0.081861,9
10,0.011590,0.003022,0.005680,0.000688,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.693401,0.535567,0.660427,0.639576,0.650830,0.635960,0.053312,4
11,0.008162,0.001675,0.006347,0.001022,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.742677,0.538687,0.466221,0.573605,0.578798,0.579998,0.090729,14
12,0.002415,0.001366,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001722,0.000148,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.015683,0.002714,0.004794,0.001057,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.598949,0.562725,0.653083,0.655522,0.457903,0.585636,0.072734,10
15,0.015236,0.001635,0.005297,0.000564,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.474664,0.671793,0.560657,0.649078,0.544572,0.580153,0.072004,13
16,0.018204,0.001305,0.004966,0.000978,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.711492,0.646862,0.511491,0.649529,0.312968,0.566469,0.142604,15
17,0.015795,0.001497,0.006642,0.001883,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.682737,0.699449,0.600046,0.608901,0.540623,0.626351,0.058084,5
18,0.001576,0.000417,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001618,0.000340,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.009533,0.002221,0.005248,0.000719,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.782794,0.529538,0.671214,0.724866,0.610782,0.663839,0.088069,1
21,0.008026,0.001172,0.005073,0.000484,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.651994,0.648393,0.552812,0.403860,0.657545,0.582921,0.097566,12
22,0.008089,0.000318,0.004883,0.000549,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.720236,0.588410,0.640371,0.503310,0.471226,0.584711,0.090536,11
23,0.006791,0.000442,0.003913,0.001118,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.519993,0.541413,0.607021,0.592087,0.464577,0.545018,0.051322,16

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

Age: 30
BMI: 40
Children: 3
Sex Male 0 or 1: 1
Smoker yes 0 or 1: 1

In [11]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction={}'.format(Future_Prediction))

Future_Prediction=[43753.33705]

C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(