In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset= pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep= dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
37 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.60081486 0.56692459 0.61843354 0.56256432
        nan        nan 0.55684455 0.63103505 0.58029692 0.60394911
        nan        nan 0.57029332 0.60486218 0.59499853 0.61330339
        nan        nan 0.58273082 0.58815288 0.58866956 0.59662917]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'}

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002874,0.000653,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002769,0.000200,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.019895,0.006450,0.007891,0.005656,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.585216,0.581869,0.679520,0.488408,0.669062,0.600815,0.069411,6
3,0.007607,0.001615,0.003703,0.000773,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.618346,0.566114,0.522802,0.597227,0.530133,0.566925,0.037050,14
4,0.008480,0.002048,0.005223,0.001458,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.690993,0.670209,0.672965,0.614069,0.443931,0.618434,0.090983,2
5,0.006782,0.000884,0.004323,0.000551,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.658386,0.598235,0.551230,0.439392,0.565578,0.562564,0.071782,15
6,0.002313,0.001004,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001641,0.000113,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.005828,0.000968,0.003502,0.000683,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.708663,0.502338,0.682597,0.442232,0.448393,0.556845,0.115526,16
9,0.006961,0.001193,0.004233,0.000634,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.674290,0.607311,0.669066,0.588584,0.615925,0.631035,0.034382,1
10,0.005934,0.000829,0.003204,0.000440,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.733681,0.571130,0.296245,0.639905,0.660524,0.580297,0.151186,12
11,0.005153,0.000448,0.003316,0.000469,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.656931,0.470498,0.700603,0.617261,0.574452,0.603949,0.078747,5
12,0.001203,0.000359,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001363,0.000326,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.015176,0.002877,0.003562,0.000916,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.728434,0.590051,0.593705,0.413433,0.525843,0.570293,0.102497,13
15,0.011690,0.001908,0.003267,0.000727,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.692892,0.606245,0.670809,0.592914,0.461451,0.604862,0.081006,4
16,0.016508,0.002374,0.003649,0.000297,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.739228,0.362684,0.628758,0.663863,0.580460,0.594999,0.127174,8
17,0.013752,0.001369,0.003576,0.000600,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.693616,0.554091,0.609365,0.521086,0.688358,0.613303,0.069439,3
18,0.001016,0.000103,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001818,0.000488,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.007074,0.000793,0.003573,0.000521,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.620441,0.561691,0.608048,0.559802,0.563673,0.582731,0.026056,11
21,0.006180,0.000671,0.003021,0.000567,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.690044,0.421387,0.637102,0.583736,0.608495,0.588153,0.090578,10
22,0.006154,0.000481,0.003290,0.000574,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.428043,0.557171,0.669235,0.580825,0.708073,0.588670,0.097573,9
23,0.004772,0.001220,0.002425,0.000303,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.759704,0.519694,0.613076,0.491895,0.598777,0.596629,0.093549,7

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

Age: 30
BMI: 40
Children: 3
Sex Male 0 or 1: 1
Smoker yes 0 or 1: 1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction={}'.format(Future_Prediction))

Future_Prediction=[13831.1152]